<?php 
	include("includes/header.php");
	include("includes/menu_esq.php");
	include("includes/menu_dir.php");
?>
</br>
</br>

<h1>Entrevista</h1>
<div class="align_center">
    <p>Domingo, 1 de julho de 2008<br />
    <b style="font-size: 14px">Emília Ferreiro <br />
    Nova Escola </b><br /><br />
    <i>Para a psicolingüista argentina, o que se espera de um leitor muda com o tempo. Na era da internet, seletividade e rapidez são características essenciais.</i><br /><br />
    <b>Denise Pellegrini, de Brasília</b><br /><br />
    Nos anos 70, ela revolucionou a alfabetização ao explicar como as crianças aprendem. Passou a defender a utilização de textos variados, em substituição às cartilhas. Após a polêmica inicial, suas teses se tornaram referência internacional. A fama não a desviou, no entanto, da preocupação em desvendar o processo de aquisição da leitura e da escrita. Aos 64 anos, Emilia Ferreiro agora avalia a interferência das inovações trazidas pela internet. "Todo profissional deve querer saber sempre mais", ensina. "Se não há inquietude, repetimos coisas que podem estar ultrapassadas." Em abril, a psicolingüista argentina (que vive no México) passou pelo Brasil e concedeu a seguinte entrevista a NOVA ESCOLA<br /><br />
    
    <b>NOVA ESCOLA> No livro Cultura Escrita e Educação, a senhora afirma que adora pesquisar e descobrir que entendeu algo que a intrigava. O que a deixa intrigada atualmente?</b><br /><br />
    <b>Emilia Ferreiro<</b> Continuo tentando compreender melhor o funcionamento dos sistemas e das tecnologias de escrita. Indagações surgem a respeito dos modos de comunicação e estilos que estão sendo criados. Um exemplo é o chat, que parece um intercâmbio informal, cara a cara, só que por texto. Outro é o e-mail, que não é uma carta em papel nem um telegrama. Essas novas formas de diálogo possuem propriedades que não conhecemos. São temas a ser pesquisados, assim como a interface entre a aquisição da escrita com letras e com números... <br /><br />
    <b>NE> Como isso se dá?</b><br /><br />
    <b>Emilia<</b> As duas são ensinadas simultaneamente porque a escola e o ambiente pedem. Já conhecemos bastante o sistema de aquisição da leitura com letras e a maneira de escrever números em situações vinculadas a representações de quantidade. Quero averiguar como se descobre quando usar um ou outro. Quando escrevo casa, leio casa e posso traduzir para house, se souber inglês. No entanto, se escrevo 5, posso ler cinco ou five. Nesse caso não está escrito o nome do número mas o sentido que ele passa. E esse sentido pode ser passado em qualquer língua. Não posso redigir a palavra casa com números, mas a palavra cinco posso escrever também com um algarismo. É interessante ver como crianças muito pequenas, de 4 ou 5 anos, lidam com isso.<br /><br />
    <b>NE> O professor deve tentar desvendar problemas em seu dia-a-dia?</b><br /><br />
    <b>Emilia<</b> Não. O ofício do pesquisador e o do professor são distintos. Digo isso porque exerço os dois. Quando estou ensinando, minha atitude sobre os problemas é diferente da que tenho quando estou pesquisando. É importante ensinar os alunos a pesquisar, mas isso é parte de meu trabalho de professora.<br /><br />
    <b>NE> Mas não é também papel do docente buscar novos conhecimentos?</b><br /><br />
    <b>Emilia<</b> Com certeza. Só que isso é diferente de pesquisar. Querer saber sempre mais deve ser próprio de qualquer profissional. Um médico também tem de se atualizar e não se contentar com o que aprendeu na universidade. Se não há uma certa inquietude em continuar descobrindo coisas novas terminamos repetindo as antigas — e o que era válido há vinte anos não continua necessariamente bom hoje.<br /><br />
    <b>NE> O significado de saber ler e escrever também muda com o tempo?</b><br /><br />
    <b>Emilia<</b> Usamos esses mesmos verbos na Grécia clássica, na Idade Média, na revolução industrial ou na era da internet. Por isso, temos a impressão de que designam a mesma coisa. O real significado, no entanto, vem se modificando. Ambos têm a ver com marcas visuais, mas o que se espera do leitor é determinado socialmente, numa certa época ou cultura. Na Antigüidade clássica não se esperava o mesmo que no século XVIII, nem o que se espera agora.<br /><br />
    <b>NE> O que determina a eficiência de um leitor na era da internet?</b><br /><br />
    <b>Emilia<</b> O trabalho na internet exige rapidez na leitura e muita seletividade, porque não se pode ler tudo o que está na tela. E a capacidade de selecionar não é algo que, há alguns anos, fosse uma exigência importante na formação do leitor. No contexto escolar, não tinha lugar preponderante mesmo. Na rede mundial de computadores, as páginas estão cheias de coisas que não têm relação com o que procuro e existe a possibilidade de um texto me conduzir a outros por meio de um click. Além disso, quando tenho um livro em mãos e o abro em qualquer página, sei claramente se é o começo, o meio ou o fim. Quando abro uma página na internet nem sempre tenho noção de onde estou.<br /><br />
    <b>NE> Mas os jovens têm facilidade para se adaptar a essas mudanças...</b><br /><br />
    <b>Emilia<</b> Eles aprenderam a usar a internet sozinhos e rapidamente, sem instrução escolar nem paraescolar. Eles conhecem essa tecnologia melhor que os adultos — os alunos sabem mais do que seus mestres. Essa é uma situação de grande potencial educativo, porque o professor pode dizer: "Sobre isso eu não sei nada. Você me ensina?" A possibilidade de uma relação educativa realmente dialógica é fantástica. Mas o docente não está acostumado a fazer isso e, num primeiro momento, fica com muito medo de não poder ensinar. Em casa, ele recorre aos filhos. No espaço público, na escola, ele tem mais dificuldades.<br /><br />
    <b>NE> Além da questão tecnológica, existe a da língua. A senhora acha que quem não souber inglês será um analfabeto nesta era da internet?</b><br /><br />
    <b>Emilia<</b> É preciso aprender o inglês, sem dúvida, mas não só esse idioma. Nestes tempos de globalização, vemos ao mesmo tempo um movimento de homogeneização (de um lado) e grupos que manifestam um desejo de manter a própria identidade (de outro). As duas coisas estão funcionando simultaneamente. No início da internet tínhamos a impressão de que ela seria uma das tantas maneiras de converter o inglês na única língua de comunicação. Hoje a situação mudou bastante. Há cada vez mais uma diversidade de idiomas na rede. Temos duas direções a seguir: consultar somente sites na nossa língua ou tomar consciência de que a rede nos dá acesso, por exemplo, a jornais escritos em países distintos — e procurar entendê-los.<br /><br />
    <b>NE> Voltando à alfabetização, o livro Psicogênese da Língua Escrita foi lançado no Brasil em 1985 e causou uma revolução. Como a senhora avalia a repercussão da teoria ali contida?</b><br /><br />
    <b>Emilia<</b> As mudanças educativas são lentas. É muito fácil transformar uma escola pequena, privada, que tenha desejo de evolução. Mas num sistema educativo municipal ou estadual é mais difícil. Tendo em conta a complexidade da realidade brasileira e levando em consideração que a difusão da teoria não foi similar em todas as regiões, eu diria que já aconteceram muitas coisas por aqui.<br /><br />
    <b>NE> Quais as mais significativas?</b><br /><br />
    <b>Emilia<</b> No Brasil havia uma espécie de obsessão em montar turmas homogêneas. Tenho a impressão de que esse não é mais um problema. E se isso realmente aconteceu, é um grande avanço. A homogeneidade é um mito que nunca se alcança. Eu posso aplicar uma prova, dizer que vinte estudantes são iguaizinhos e colocá-los todos juntos para trabalhar. Daqui a uma semana eles não serão mais iguais, porque os ritmos de desenvolvimento são muito variados. Uma coisa são os ritmos individuais, outra, as etapas de desenvolvimento.<br /><br />
    <b>NE> Com relação às etapas de desenvolvimento, você crê que sua importância já foi assimilada?</b><br /><br />
    <b>Emilia< </b>Num primeiro momento, houve apenas a troca de rótulos. Os fracos passaram a ser chamados de pré-silábicos. Os que estavam no meio do processo eram os silábicos e os que eram fortes foram classificados como alfabéticos. Alguns anos depois ficou mais claro que os rótulos novos permitiam ver de outra maneira o progresso das crianças, mostravam que elas estavam aprendendo. É desesperador estar diante de um aluno e dizer "ele não sabe", "ele ainda não sabe". Quando se pode visualizar as mudanças como um progresso na aprendizagem, tudo muda. Primeiro porque o esforço de aprender é reconhecido; segundo porque há a satisfação de ver avanços onde antes não se enxergava nada.<br /><br />
    <b>NE> Ainda hoje chegam cartas à redação de NOVA ESCOLA perguntando qual a idade ideal para iniciar a alfabetização...</b><br /><br />
    <b>Emilia<</b> Constatei que, atuando de forma inteligente, pode-se alfabetizar aos 5 anos, aos 6 ou aos 7. É preciso oferecer oportunidade para os menores. Alguns vão aprender muito, outros nem tanto. A idéia de que eu, adulto, determino a idade com que alguém vai aprender a escrever é parte da onipotência do sistema escolar que decide em que dia e a que horas algo vai começar. Isso não existe. As crianças têm o mau costume de não pedir permissão para começar a aprender.<br /><br />
    <b>NE> O que um alfabetizador não pode deixar de fazer em classe?</b><br /><br />
    <b>Emilia<</b> Ler em voz alta. Especialmente se as turmas forem pobres, vindas de lugares em que há poucas pessoas letradas. Essa poderá ser a primeira vez que ela passa por uma experiência assim. O texto, no entanto, tem de ser bom e lido com convencimento. Esse aluno de 6 ou 7 anos vai presenciar um ato quase mágico. Vai escutar um idioma conhecido e ao mesmo tempo desconhecido, porque a língua, quando escrita, é diferente. Essa maneira de trabalhar é muito melhor do que usar as cartilhas e as famílias silábicas.<br /><br />
    <b>NE> As cartilhas, aliás, já não são usadas como antigamente.</b><br /><br />
    <b>Emilia<</b> Certa vez um editor brasileiro me acusou de estar arruinando o negócio de cartilhas, e parece que ele tinha razão. Se tenho mesmo relação com a queda na produção desses livros, estou muito orgulhosa. Eles eram de péssima qualidade, horríveis, assustadores. Eram pura bobagem. Apesar disso, há vinte anos parecia um sacrilégio, no Brasil, dizer que a família silábica não era a melhor maneira de trabalhar. Tenho a impressão de que isso mudou e de que esse é um caminho sem volta. Para ensinar a ler e escrever é necessário utilizar diferentes materiais. Um livro só não basta. É preciso utilizar livro, revista, jornal, calendário, agenda, caderno, um conjunto de superfícies sobre as quais se escreve. A maneira como um jornal é redigido não é a mesma que se encontra num livro de Geografia ou História.<br /><br />
    <b>NE> Como deve agir o professor em áreas rurais, onde o contato com a língua escrita é muito menor? </b><br /><br />
    <b>Emilia< </b>Ele não pode desperdiçar nem um minuto do tempo em que sua turma está na escola, porque cada minuto é muito precioso. Terminado o período da aula, o contato com a escrita quase desaparece, sobretudo se for numa região em que não haja maquinários sofisticados, que exigem a leitura de manuais, ou onde materiais impressos praticamente não existam.<br /><br />
    <b>NE> Como a senhora avalia a alfabetização na América Latina?</b><br /><br />
    <b>Emilia<</b> A América Latina está conseguindo levar praticamente todas as crianças para a escola, mas nem todas continuam estudando nem aprendem algo que justifique sua permanência ali.<br /><br />
    <b>NE> Ou seja, ainda há o risco de o continente continuar formando analfabetos funcionais.</b><br /><br />
    <b>Emilia></b> Esse problema ocorre no mundo inteiro, ainda que com nomes diferentes. Na França, por exemplo, há uma distinção entre o iletrado e o analfabeto. Este não teve uma escolaridade suficientemente prolongada. O primeiro teve essa oportunidade, mas não pratica nem a leitura nem a escrita. Então, poucos anos mais tarde, lê com dificuldade e evita escrever. Países que já resolveram o problema da escolaridade obrigatória têm iletrados; os que não possibilitaram à população a escolaridade básica têm analfabetos.<br /><br />
    <b>NE> O Brasil encontrou o caminho para combater esse problema?</b><br /><br />
    <b>Emilia></b> No Brasil, aparentemente, está em curso uma mudança sensível em relação à escolarização. Muito mais crianças e jovens em idade escolar estão nas salas de aula. Esse é o primeiro passo. Agora, vem o mais importante: desafio da qualidade, da aprendizagem. Não basta ocupar todas as carteiras. É preciso ensinar.<br /><br />
    <br />
    <a href="javascript:history.go(-1)"><img src="img/icone_voltar.png"/></a>
    
    </p>


</div>

<?php
	include("includes/footer.php");
?>