<?php 
	include("includes/header.php");
	include("includes/menu_esq.php");
	include("includes/menu_dir.php");
?>

</br>
</br>

<h1>Entrevista</h1>
<div class="align_center">
    <p>Sábado, 1 de janeiro de 2000<br />
    <b style="font-size: 14px">Isabel Solé <br />
    Revista Pátio</b><br /> <br />
    
    <i>"Na escola, não se aprende só a ler, mas também maneiras de ser leitor"</i><br /><br />
    A espanhola Isabel Solé dedicase há anos à pesquisa sobre o ensino e a aprendizagem da leitura, os processos envolvidos na compreensão leitora e sua vinculação com a aprendizagem. Professora do Departamento de Psicologia Evolutiva e da Educação na Universidade de Barcelona, Isabel Solé é também autora de diversos livros, dos quais três foram publicados em português pela Editora Artmed: Estratégias de Leitura, Aprender e Ensinar na Educação Infantil, em colaboração com Eulalia Bassedas e Teresa Huguet, e o recém-lançado Assessoramento Psicopedagógico, organizado em conjunto com Carles Monereo. A Artmed também está produzindo seu livro Orientação Educacional e Intervenção Psicopedagógica. Na entrevista a seguir, concedida à Pátio por e-mail, Isabel Solé aborda várias questões inquietantes para os educadores que trabalham com alfabetização.
    <br /><br />
    <b>Pátio - Muitos países da América Latina estão preocupados com o analfabetismo. O combate a esse problema continua fazendo parte dos programas de governo de esquerda e de direita. Como a senhora vê a situação da alfabetização hoje na América Latina?</b><br /><br />
    <b>Isabel Solé</b> - Não disponho de conhecimento suficiente sobre as políticas de alfabetização na América Latina para responder concretamente a essa pergunta. Posso apenas apontar que o analfabetismo é um fator de exclusão social e de marginalização, por isso parece lógico que os governos sintam a urgência de erradicar tal problema, especialmente se se trata de um governo de linha progressista, que deve ter na construção de uma sociedade mais justa, igualitária e coesa um de seus principais objetivos. Sem que pressuponha nenhum menosprezo pelas pessoas analfabetas, é evidente que nas sociedades letradas elas se encontram em desvantagem em relação aos alfabetizados. Por outro lado, a crescente presença das novas tecnologias da informação e da comunicação exige políticas decididas que garantam a todos os cidadãos o acesso a essas tecnologias, o que comporta um duplo esforço de alfabetização: na linguagem oral e escrita e nos sistemas e códigos de comunicação próprios de tais meios. Não há dúvida de que os desafios são muitos e não abordá-los traz o risco certo de estabelecer novas rupturas e distinções entre os cidadãos: os que possuem as estratégias necessárias para atuar na sociedade da informação e do conhecimento, e podem, portanto, intervir ativamente nela, e os que não as possuem e ficam excluídos.<br /><br />
    <b>Pátio - Depois de um período de foco no repensar e no reconceitualizar o processo de aquisição da leitura e da escrita, estamos vivendo hoje um momento de sistematizar novas metodologias e buscar recursos para a continuação do processo para além da primeira série. Como a senhora analisa este momento?</b><br /><br />
    <b>Isabel Solé</b> - Com profunda satisfação. Sempre defendi um enfoque amplo no ensino da leitura que inclua aprender a ler; aprender a aprender através da leitura e aprender a divertir-se lendo. Um enfoque desse tipo exige que a leitura seja considerada como uma questão de projeto escolar, de modo que em cada ciclo e cada nível, da Educação Infantil até o Ensino Médio, sejam contemplados conteúdos específicos de leitura. Quando as crianças já aprenderam a ler autonomamente, resta um longo caminho a percorrer que, na verdade, não termina nunca. Na escola, esse caminho inclui, por um lado, a aprendizagem e o uso competente das estratégias de leitura para aprender a partir de textos: saber dotar-se de objetivos de leitura, saber integrar a nova informação com o conhecimento prévio disponível, saber discernir entre a informação fundamental e a secundária, saber buscar, resumir; sintetizar e reorganizar a informação, saber ler a partir de diferentes fontes... e outras. Por outro lado, na escola, os meninos e as meninas devem encontrar múltiplas oportunidades de desfrutar da leitura: da que outros fazem para eles e da leitura própria, pessoal e independente, vinculada a uma ampla variedade de gêneros. Entendida desse modo, a leitura tem um lugar ao longo de toda a escolaridade; na escola, não se aprende só a ler, mas também se aprendem maneiras de ser leitor, algumas mais funcionais, outras mais restritivas.<br /><br />
    <b>Pátio - É inegável que a alfabetização, ou melhor, o recurso de ser alfabetizado é um instrumento que possibilita a inserção dos indivíduos na sociedade e na cultura. Tal inserção possibilita uma vida mais criativa, participativa e integrada na sociedade. Sabe-se que o fracasso escolar e a expulsão da escola que ocorrem hoje estão criando os analfabetos de amanhã. Como enfrentar esse problema estrutural?</b><br /><br />
    <b>Isabel Solé</b> - Como se pode intuir pela minha resposta à primeira pergunta, considero que ser alfabetizado constitui, nas sociedades letradas, um direito que deve estar ao alcance de todos os cidadãos. Cada vez que um aluno abandona a escola sem ter-se apropriado dos instrumentos básicos de leitura e escrita, fica claro que a sociedade fracassa em seu empenho de dotar seus membros dos recursos necessários para participar ativamente dela. Os fatores que confluem na desmotivação, no absenteísmo escolar, na impossibilidade de dar resposta às dificuldades que determinados alunos encontram para permanecer na escola e para aprender com as oportunidades que lhes são oferecidas são muitos e em sua imensa maioria não têm uma única causa, nem se originam em uma só instituição. A escola não pode enfrentar sozinha problemas cuja gestação e manutenção devese, em boa parte, a profundas desigualdades sociais.<br />Isto posto, é preciso pensar que, se as condições pessoais e sociais dos alunos que chegam às escolas são diferentes - como também os próprios ambientes, a cultura, a organização e o funcionamento de cada centro docente -, a resposta educativa a essa diversidade (de interesses, de capacidade, de conhecimento, de recursos) não poderá ser uma resposta homogênea, que só será proveitosa para alguns, mas excluirá outros. Diante de uma resposta rígida, inflexível, distanciada de suas necessidades, muitos alunos não poderão aprender, nem suportar uma instituição à qual não podem adaptar-se, e esta acabará excluindo-os. <br />Quando a escola não pode ensinar a alguns alunos suas linguagens - a linguagem oral especifica da escola e a linguagem escrita -, não há dúvida de que está sendo forjado seu fracasso e o desses alunos, que se vêem desprovidos dos instrumentos que a própria escola exige para participar dela. Disso se deduz que as prioridades devem fixar-se, no que se refere a esse aspecto, em conseguir um ambiente alfabetizador, capaz de incorporar alunos diferentes, de prever suas dificuldades, de otimizar seus recursos e, quando for necessário, de executar as ações especificas necessárias para corrigir e compensar os desajustes e as dificuldades que alguns, sem dúvida, encontrarão. Isto exige não só uma mudança nos conceitos sobre o que significa aprender a ler e nos procedimentos mediante os quais se torna acessível a leitura a alunos distintos, mas também em atitudes que influem inquestionavelmente no ensino. Nesse sentido, é necessário questionar e deixar de aceitar o fato de que um considerável número de alunos não possa aprender a ler e a escrever. Esses alunos estarão quase indefectivelmente destinados ao fracasso, o que nos deveria fazer refletir sobre nossas práticas e reorientá-las.<br /><br />
    <b>Pátio - Ao mesmo tempo em que se discute um conceito de alfabetização ampliado, que envolva alfabetizar-se em vários sistemas simbólicos, também se discute o conceito de iletrismo, que aponta a ausência de práticas de leitura que garantam a existência de um leitor no sentido amplo. Como podemos entender essas mudanças conceituais?</b><br /><br />
    <b>Isabel Solé</b> - Em minha opinião, tais mudanças devemse, em parte, às novas necessidades das sociedades tecnologicamente avançadas, que exigem um leitor efetivamente preparado para ler textos e suportes inimagináveis há apenas algumas décadas, e, em parte, às concepções atuais sobre a leitura, muito distanciadas de sua caracterização como mecanismo ou sistema de decodificação, cujo domínio transformava o analfabeto em uma espécie de "leitor universal". A perspectiva cognitivo-construtivista evidenciou a complexa interação entre o texto e o leitor responsável pela construção do significado, assim como a dimensão profundamente cultural da leitura, que se traduz, entre outros aspectos, nos usos culturais que dela se privilegiam e no caráter culturalmente mediado do que se lê e escreve. Isto é, ser leitor significa ser capaz de ler textos muito diversos para alcançar finalidades múltiplas: os textos e as finalidades que cada grupo social define como constitutivos de sua cultura. Por isso, comentava em uma resposta anterior, que nas escolas não só se aprende a ler, mas também se aprendem maneiras de ser leitor. Alguns alunos aprendem a ler estritamente para passar pela escola com mais ou menos altos e baixos; pode ser que sua leitura seja muito pobre, que não lhes permita o acesso a outros textos ou outros objetivos distintos, necessário, entretanto, do ponto de vista de sua inserção social e para sua formação pessoal. Nesse caso, estamos muito longe da idéia de leitor em sentido amplo, que poderíamos definir como aquele que pode utilizar a leitura para satisfazer as necessidades pessoais, profissionais, de formação contínua e de caráter único que encontrará em seu ciclo vital. É por esse motivo que se insiste, com razão, em que a escola não prepara para ela mesma, mas para a vida, aspecto que as práticas educativas em torno da alfabetização não deveriam negligenciar.<br /><br />
    <b>Pátio - A Educação Infantil também tem um papel importante na alfabetização? Como redefinir esse papel à luz das novas perspectivas educacionais?</b><br /><br />
    <b>Isabel Solé</b> - A Educação Infantil tem um papel importantíssimo na formação das meninas e dos meninos em todas as suas capacidades e, é claro, também no que se refere à alfabetização. Quando a escola infantil organiza atividades relevantes do ponto de vista social e promove a participação dos pequenos nessas atividades, de modo que, progressivamente, possam apropriar-se dos conteúdos (estratégias, valores, noções, conceitos, atitudes, etc.) em torno dos quais se desenham essas práticas, sem dúvida está favorecendo seu desenvolvimento. A escola infantil, do ponto de vista da alfabetização, tem um papel crucial para que as crianças se interessem pela leitura e pela escrita, para que possam formular perguntas sobre elas e encontrar respostas a suas interrogações, em uma perspectiva que assume que o acesso ao significado e o gosto pela leitura são componentes essenciais na formação das crianças e que entende que o domínio do código é uma condição necessária, mas não suficiente, para a leitura autônoma.<br />O conhecimento de que dispomos na atualidade mostra que os meninos e as meninas enfrentam desde muito pequenos os problemas que lhes sugere a presença do escrito e suas próprias necessidades de ler e escrever. As soluções mais ou menos convencionais que elaboram para esses problemas indicam como os representam e oferecem aos professores numerosas pistas para intervir. Essa intervenção exige, entretanto, um conhecimento sobre os processos de leitura e de escrita que permita ir além da mera aplicação de uma metodologia, dos mitos e das modas imperantes e de práticas que, às vezes, carecem de fundamento, mas instalam-se nas escolas com facilidade assombrosa. A discussão sobre a leitura em Educação Infantil é um tema apaixonante e delicado; expor em detalhes minha posição excede os limites que impõe uma entrevista como esta e exige, provavelmente, outro formato. Mas posso resumi-la com o título de um artigo que escrevi há algum tempo: Ler em Educação Infantil? Sim. Obrigada! (mas com condições).1<br /><br />
    <b>Pátio - Um grande problema que a escola continua enfrentando é a avaliação da aprendizagem de leitura e escrita. Do seu ponto de vista, o que e como se deve avaliar? O que priorizar? É possível repensar a avaliação?</b><br /><br />
    <b>Isabel Solé</b> - Com freqüência, a avaliação da leitura leva em conta basicamente as notas obtidas pelos alunos em uma prova de leitura expressiva, baseada na velocidade e na precisão, ou em um questionário de perguntas pós-leitura, e desconsideram-se, injustificadamente, as observações mais informais que se pôde fazer ao longo de um processo mais amplo. o qual inclui situações variadas de leitura. A literatura existente sobre o tema e os dados de pesquisa demonstram que, por um lado, à luz do que hoje sabemos sobre a leitura, sua avaliação é bastante restritiva e estereotipada e que, por outro, situações de avaliação aparentemente muito parecidas em nível superficial (elaborar resumos, responder a perguntas após um texto lido, etc.) escondem, na realidade, níveis de complexidade bastante diversos, para os quais confluem distintas variáveis que interagem entre si, sem que se esteja muito consciente desse fato. Aprofundar o conhecimento do que se avalia efetivamente (A memorização? A compreensão inferencial? O reconhecimento literal?) e ensaiar novos meios para que a avaliação seja um ingrediente essencial de um ensino diversificado aparecem como desafios nos quais é preciso avançar. Repensar a avaliação da leitura só é possível a partir de uma reconceituação da própria leitura, sem a qual nem as práticas de ensino nem as de avaliação podem modificar-se além de aspectos superficiais.<br /><br />
    <b>Nota
    1. Artigo publicado na Pátio, n. 7, nov/98 - jan/99.</b>
    
    <br />
    <br />
    <a href="javascript:history.go(-1)"><img src="img/icone_voltar.png"/></a>
    </p>
    </p>

</div>

<?php
	include("includes/footer.php");
?>