<?php 
	include("includes/header.php");
	include("includes/menu_esq.php");
	include("includes/menu_dir.php");
?>

</br>
</br>

<h1>Entrevista</h1>
<div class="align_center">
    <p>Segunda-feira, 23 de junho de 2008<br />
    <b style="font-size: 14px">Rosa Antunes<br />
    Avisa Lá</b><br />
<br />    
    A escrita do nome próprio é uma das mais importantes conquistas da criança que se alfabetiza. Para a criança, o conjunto de letras que compõem seu nome diz algo sobre sua identidade, filiação, sua própria história. Além disso, a escrita do nome próprio tem papel fundamental no processo de alfabetização da criança, representa um passo importante de sua entrada no mundo da escrita.<br /><br />
    Dada a importância do tema para a prática docente, convidamos a especialista Rosa Maria Antunes de Barros para tratar do assunto. Rosa tem uma larga experiência na docência para as séries iniciais, tendo passado pelas redes municipais de ensino de São Paulo e também pela rede estadual. Atualmente é coordenadora de classes de primeiro ano em uma escola privada em São Paulo, mas não desiste da escola pública. Ela também trabalha na secretaria municipal de educação, dedicando-se às questões do ensino no ciclo 2 (crianças de 5ª à 8ª série). Rosa também participou do PROFA, o Programa de Formação de Professores Alfabetizadores.<br /><br />
    Nessa entrevista, Rosa responde às questões didáticas referentes ao uso da lista de nomes próprios no planejamento das atividades de alfabetização inicial, tema já abordado pela autora em seu texto O papel pedagógico do nome próprio, publicado no material de apoio do PROFA, módulo 2. O roteiro da entrevista é fruto de um trabalho de formação: os alunos do curso on line O papel pedagógico do nome próprio na alfabetização inicial leram seu texto e trouxeram para o fórum de discussão, a pedido da tutora, as perguntas que gostariam de fazer à autora. Desse ponto de vista, esta entrevista representa a voz dos professores e reais dúvidas.<br /><br />
    
    <b>Aém das Letras:</b> Para começar, Rosa, ajude-nos a contextualizar o assunto que você vai tratar nessa entrevista. Por que o nome próprio é tão importante na alfabetização inicial?<br /><br />
    <b>Rosa:</b> O trabalho com os nomes não se refere apenas às crianças, mas também aos adultos que estão se alfabetizando. Saber escrever o nome tem um valor social muito grande. Eu trabalho com os nomes até onde eles podem ajudar as crianças a avançarem. Ele é uma fonte de consulta, uma referência para elas poderem ler ou escrever outras palavras. E o que significa, hoje, saber ler e escrever? Hoje nós falamos de uma alfabetização que coloca para os alunos dois desafios: aprender a ler e a escrever convencionalmente e, em paralelo, vivenciar diferentes situações de uso da leitura e da escrita. Enquanto o aluno está aprendendo a ler convencionalmente, também esperamos que eles possam aprender para quê que serve ler e escrever. Quais são as atividades de alfabetização que ajudam as crianças a refletir e a compreender o sistema? Os professores têm um repertório de situações que pode lançar mão: o trabalho com a ordenação de textos, a leitura de textos de memória, a leitura de listas. Paralelo a isso, o professor deve ler muito, criar contextos para os projetos, situações que favoreçam conhecer outros gêneros textuais e que tenham um propósito didático, um propósito social. Por exemplo, produzir textos para confeccionar um livro, recitar poesias para fazer um sarau, confeccionar livros de brinquedos para ensinar crianças de outras escolas. Ou seja, tudo isso caminha junto. O trabalho com o nome próprio não é isolado e não resolve todos os problemas da alfabetização.<br /><br />
    <b>Além das Letras:</b> Em síntese, a criança aprende como, o que e para que se escreve. Mas muitas nem mesmo sabem que a escrita representa a fala. Sobre isso, a professora Lorena quer saber quais são as situações que os professores podem propor para que esse aluno compreenda que a escrita representa a fala.<br /><br />
    <b>Rosa:</b> Quando o professor está lendo diariamente para as crianças, ou um aluno que já está alfabetizado está lendo para o restante da sala, as crianças podem aprender que a escrita representa a fala, quer dizer, elas observam que as pessoas estão lendo aquilo que está escrito lá. Uma outra proposta comum é a leitura de textos que as crianças sabem de memória. No começo do ano os professores levantam todo o repertório de músicas, de parlendas, de canções, de quadrinhas, de trava línguas que as crianças conhecem de memória. Então, oferecem os textos escritos para que as crianças possam ler e ir ajustando o que está falando ao que está escrito. Parece uma atividade fácil, mas não é. Quando as crianças trabalham em conjunto, também podem observar que a escrita representa a fala. Por exemplo, quando uma criança está ditando para a outra escrever, às vezes a que dita nota que a que está escrevendo, de repente para. Então, a que dita fala: "não, escreve aí: joga a bola. Você ainda não escreveu". Quer dizer, a criança observa esses atos de escrita e vê que tudo que é falado está ali escrito e isso contribui para que ela veja que a escrita representa a fala. São situações de leitura feitas pelos alunos, pelo professor; situações de escrita feitas pelo professor. Por exemplo, quando eles estão elaborando textos coletivamente em que a classe dita e o professor escreve na lousa, a criança está aprendendo ali que tudo que está sendo falado, está sendo escrito. O professor escreve e fala: "Deixa eu ler para ver se todas as nossas idéias estão garantidas aqui". Aí o professor lê e assim a criança nota que há uma estabilidade da escrita, que o que é ditado, pode ser lido. <br /><br />
    <b>Além das Letras:</b> Vamos entrar, então, no trabalho pontual a partir da escrita do nome. A professora Lorena pede que você esclareça o que significa a expressão "escrita livre de contexto" que você utiliza em seu texto para definir a especificidade da escrita do nome próprio. E a Virna quer saber porque se enfatiza apenas o primeiro nome e não o nome todo.<br /><br />
    <b>Rosa:</b> O nome de uma pessoa já é uma situação singular, é uma situação única, não requer mesmo um contexto. Ele já tem uma função social e se refere a uma única pessoa, ou seja, ele não causa nenhuma ambigüidade. Essa é uma vantagem que esse tipo de escrita apresenta para a criança que está se alfabetizando. Trabalhar com uma lista de nomes é significativo para as crianças poderem compreender melhor o funcionamento do sistema alfabético. É por isso que a gente trabalha apenas com o primeiro nome. Vamos supor que na classe tenha duas Isabelas, uma Isabela Furlan e uma Isabela Gonçalves. Nesse caso é interessante colocar o segundo nome para poder diferenciar um nome do outro. Mas apenas nesse caso, para criar mais uma variável e fazer as crianças pensarem mais sobre as semelhanças e diferenças dos nomes, essa é a finalidade.<br /><br />
    <b>Além das Letras:</b> Mas a professora Clidinéia lembrou uma coisa importante. Existem pessoas, até mesmo na sala de alfabetização de adultos, que não gostam de seu nome, por algum motivo qualquer. Como abordar esses indivíduos? Qual a sugestão para a situação?<br /><br />
    <b>Rosa:</b> Isso é inevitável. Alguns nomes parecem diferentes para o grupo, por isso se destacam ou chamam a atenção e muitas vezes acabam sendo objeto de brincadeiras dos colegas, até de deboche. O nome da criança não dá pra mexer, é dado. O que a prática nos mostra é que é interessante consultar a criança sobre o nome que ela quer que conste na lista, o modo como ela gosta de ser chamada. O Francisco, por exemplo, pode dizer "Chicão". O professor sabe que o nome dele é Francisco, mas ele se reconhece, ele se vê como "Chicão", então o professor pode grafar "Chicão" na filipeta dele, na lista que será usada pelos alunos para suas consultas. Mas, se ele colocar Francisco e tentar ler "Chicão", verá que não é isso que está escrito lá. Às vezes tem criança que me pergunta: "Por que meu nome tem dois F, dois D?" Ás vezes é porque o nome vem de uma outra língua, ou porque os pais acham bonito escrever desse jeito. Isso foi uma escolha. Às vezes, há casos de crianças que até sabem a história do seu nome e contam para os seus colegas. Existem nomes que não têm nada de especial e as pessoas não gostam. Há nomes que têm alguma característica que diferencia que as pessoas também não gostam e outros gostam. Não é você que escolhe o seu nome, não há como intervir. No máximo podemos conversar com o grupo para que os alunos conheçam a história daquele nome, aquilo que lhe dá sentido, e que, por ser o nome de alguém, deve ser respeitado.<br /><br />
    <b>Além das Letras:</b> A Renata quer saber se o nome, gostando dele ou não, não exerce algum peso na formação da personalidade da criança.<br /><br />
    <b>Rosa:</b> Eu não sei se o nome está relacionado com a personalidade da criança, talvez não. Mas não importa, é preciso ter claro que o trabalho com o nome é para ajudar os meninos a aprenderem melhor e não tem uma finalidade psicológica. <br /><br />
    <b>Além das Letras:</b> A professora Renata observa que muitas crianças aprenderam a escrever seus próprios nomes e conseguem identificá-los, porém não se alfabetizam. Ela gostaria de saber sua opinião sobre a que se deve essa dificuldade, uma vez que ela utiliza muitas das propostas citadas no seu texto sobre o papel do nome próprio, do PROFA. <br /><br />
    <b>Rosa:</b> Essa questão é muito freqüente. Muitos professores já sabem que trabalhar com os nomes é interessante, mas muitas vezes não sabem como intervir, porque tem uma coisa que eu acho importante que as pessoas saibam é que não é a atividade que leva à aprendizagem, mas sim a intervenção do professor. Essa intervenção depende do conhecimento teórico que ele tem, depende do quanto ele estuda, pois quanto mais você estuda, mais sustentação dá ao trabalho. A questão não está no nome, mas na forma como eu trabalho. Hoje você vê as pessoas dizendo "eu já faço ditado, eu já faço cópia, eu já faço leitura em voz alta, eu já trabalho com o nome". A questão não é se eu já faço, é como eu faço. Além disso, também é preciso refletir sobre o que eu já falei em outro momento dessa entrevista. Atribui-se um peso muito grande ao nome como se ele fosse a salvação das crianças. O nome é importante, ele ajuda muito, mas há a necessidade de se trabalhar outras atividades. Uma coisa é identificar o nome, outra é criar condições para as crianças compreenderem o sistema. Mais uma vez enfatizo: o nome é uma das atividades que se propõe na sala de aula, mas não deve se ater só ao que está sugerido no trabalho com os nomes. A professora que está desenvolvendo um programa de alfabetização deve ter em vista muitas outras atividades além de ler e escrever o nome. Simultaneamente ao trabalho com leitura e escrita de nomes, é preciso ler textos de memória, fazer aliteração de textos, formar palavras com letras móveis, reescrever parlendas e textos que as crianças já têm de memória. É um conjunto de atividades que vão ensinar as crianças a ler e a escrever. Portanto, precisamos também pensar na diversidade de atividades, na diversidade de gêneros que ajudam as crianças a aprender mais e melhor. Não se trata apenas da quantidade de atividades, mas sim da qualidade. Como estão sendo planejadas essas atividades, como estão sendo feitas as intervenções durante as atividades, como é que são agrupadas essas crianças. <br /><br />
    <b>Além das Letras:</b> A professora Sônia quer saber se a atividade com nomes próprios poderia ser proposta tanto para os alunos alfabéticos como para os não-alfabéticos. É possível pensar um trabalho sobre esse mesmo assunto para crianças que estão em níveis diferentes e que precisam de novos desafios?<br /><br />
    <b>Rosa:</b> As situações que envolvem aprender o nome em casa, com as famílias, são bastante comuns na vida das crianças. Nós, professores, apenas incorporamos essas situações em nossa prática educativa, nós observamos que essa lista de nomes poderia dar suporte para o trabalho da alfabetização inicial. Esse trabalho favorece a reflexão sobre o sistema, mas isso não é tudo. A proposta a partir da lista de nomes faz parte de um conjunto de outras práticas docentes, o professor pode e deve trabalhar com os nomes durante todo o ano, desde que isso ajude as crianças a aprenderem melhor. Nosso objetivo é ajudar as crianças a entender, a compreender como funciona o sistema de escrita. O que a prática tem mostrado é que quando as crianças já conhecem bem o seu próprio nome e já conhecem bem os nomes dos colegas, elas querem escrever outras coisas e para isso consultam a lista de nomes da sala ou o que elas já têm de memória. É aí que elas buscam informações para saber como se escreve, por exemplo, mar, que é uma palavra que já está no nome do Marcelo. Elas utilizam os nomes para descobrir outras coisas sobre a escrita. Então, enquanto os nomes puderem servir para isso, são úteis. Mas, para os alunos alfabéticos, esse contexto acaba oferecendo poucas atividades realmente desafiadoras, então é preciso pensar outras propostas que são mais significativas para eles. <br /><br />
    <b>Além das Letras:</b> Então, esse é um trabalho muito específico das séries iniciais, não é?<br /><br />
    <b>Rosa:</b> Sim, muito especifico. No ciclo 2 (5ª a 8ª série) há professores que chamam seus alunos pelo nome e outros que fazem chamada pelo número. É uma forma que eles estabelecem de se relacionar com o aluno. Não é a mais afetiva, mas é o que eles acabam utilizando. Nesse caso, não há mais necessidade de se fazer trabalho com os nomes, a não ser que o professor tenha, por algum motivo, algum interesse em fazer a história dos nomes, a pesquisa dos nomes, mas eu não conheço nenhuma prática voltada para isso. Mas, se realmente o objetivo é ajudar os meninos a aprender a ler e escrever e os meninos já sabem, a atividade com os nomes vai deixando de ser feita e pode ser substituída por outras situações de leitura e escrita que são muito mais interessantes.<br /><br />
    <b>Além das Letras:</b> A Jaqueline, professora que participou do curso on line sobre nomes, traz uma questão que ainda é de muitos professores: qual é o papel da cópia na aprendizagem? Qual a sua opinião quanto à visão de educação na qual o objetivo da aprendizagem se reduz a atos repetitivos de cópia?<br /><br />
    <b>Rosa:</b> Utilizar um nome para identificar os objetos pessoais, seja de uso escolar ou de uso pessoal, é uma atividade interessante, que permite trabalhar com a questão da identificação. O problema está em acreditar que as crianças possam aprender por repetição. Uma atividade que se faz por repetição traz em si a idéia da cópia, a crença de que a cópia ensina a escrever. Mas, na verdade, nós copiamos para nos apropriarmos de algo e, no caso do nome, podemos dizer que as crianças o copiam com o objetivo da identificação dos objetos, de seus pertences, etc. O que nós, professores, fazemos, é aproveitar o momento em que a criança copia o nome para que ela possa refletir sobre essa escrita. A criança pode pensar: por que meu nome é escrito desse jeito? E por que alguns nomes têm mais letras do que outros? Quer dizer, é possível aproveitar essa situação para fazê-las pensar. Quando a criança tem o nome memorizado, o seu próprio nome ou o nome dos colegas, pode servir-se desse conhecimento para consultas, para poder ler e escrever outras palavras. Por isso trabalhamos bastante com o nome no início do processo de alfabetização.<br /><br />
    <b>Além das Letras:</b> Silvia, uma professora do ensino fundamental, tem um caso curioso em sua turma. Ela conta que uma das crianças do grupo, de 8 anos, só reconhece o nome próprio se ele estiver escrito sozinho, se estiver em uma lista com outros nomes não o reconhece mais. O que fazer nesse caso?<br /><br />
    <b>Rosa:</b> A partir da pergunta feita pela professora, fica difícil juntar elementos necessários para responder precisamente a essa questão. No entanto, ela me faz levantar algumas hipóteses. Uma delas, diz respeito ao fato de um menino de 8 anos não conhecer ainda o próprio nome. Teria ele tido oportunidades de conhecer e pensar sobre a escrita do próprio nome e dos colegas? Uma outra hipótese: o professor muitas vezes trabalha com os nomes próprios, porém, isoladamente. Com isso ele põe a perder uma boa situação de aprendizagem e que certamente implicaria em estabelecer comparações. Por que meu nome se escreve sempre assim? Por que é diferente da escrita do nome do meu colega? Essas e outras perguntas só são respondidas quando se trabalha com listas de nomes desde o início. A minha sugestão é que a professora retome seus estudos do trabalho com os nomes próprios para que possa elaborar uma seqüência de atividades que ajude a criança a conhecer a escrita do próprio nome em outros contextos. <br /><br />
    <b>Além das Letras:</b> A professora Tatiane também tem uma pergunta sobre um caso que ela observa em sua sala de aula. Ela quer saber por que há alunos que mesmo tendo um modelo de escrita de seu nome em mãos, como seu crachá por exemplo, não conseguem reproduzir a escrita convencional de seu nome. O que acontece com essas crianças?<br /><br />
    <b>Rosa:</b> Isso pode ser uma coisa muito interessante. Por um lado, isso é bom. A criança tem o seu nome lá, vamos supor que ela se chama Anderson. Na hora que você pede para ele escrever o nome na folha, para realizar uma atividade, ele põe AEO. Na verdade, ele não está copiando. O nome está sobre a mesa e na hora que ele está escrevendo, ele o faz segundo a sua hipótese. Então se ele pensa que para escrever cada som deve-se colocar uma letra, então o nome Anderson tem 3 sons eu coloco 3 letras: no  A (An), D (der), O (son). Ele ainda coloca letras que fazem parte da sonoridade da palavra, ou seja, ele está escrevendo segundo a sua hipótese. É interessante! Ele está pensando sobre o sistema de escrita.<br />
    Mas ainda há mais um aspecto a considerar: o professor precisa ensinar às crianças o procedimento de copiar. Parece que é uma atividade simples, mas para a criança não é, mesmo para as crianças alfabetizadas. É preciso ensinar o procedimento, mostrar que quando se está copiando o nome, tem que fazer um registro fiel daquilo que está escrito lá na filipeta, no cartaz da sala. Tem que obedecer a uma ordem. Então, copiar é um procedimento que precisa ser ensinado. Para uma criança que já está alfabetizada, já está lá na segunda série, que hoje é o terceiro ano, muitas vezes o professor pede que ela copie da lousa algo que seja importante que ela copie. Claro que ninguém pedirá que se copie por copiar. Depois, na hora que o professor olha o caderno, observa uma série de erros. Isso acontece porque a criança olha pra lousa, lê o que está escrito e interpreta segundo a sua hipótese. Isso demonstra que aquilo que ela copiou, na verdade é o que ela entendeu. Ela escreve como pensa, sem se preocupar com o procedimento de copiar, mas preocupando-se, sim, em registrar o que ela leu, por isso é que a criança copia errado. Nesse caso, ela precisa aprender que está fazendo uma cópia e cópia tem que ser igual ao que está na lousa, obedecer a algumas convenções. Não se trata de nenhum problema, basta identificarmos o que está acontecendo com a criança. Ou ela está escrevendo segundo a sua hipótese, caso ela não seja alfabetizada, ou ela ainda não sabe o procedimento de copiar e aí isso precisa ser ensinado, porque ela lê, interpreta e escreve como ela pensa que é.<br /><br />
    <b>Além das Letras: </b>A professora Erotides traz a seguinte questão: ela costuma trabalhar o nome intensamente durante as primeiras semanas de aula da 1a série, porém, ao mesmo tempo, ela coloca no crachá de mesa o nome e sobrenome com os dois tipos de letra. De um lado, o primeiro nome com letra bastão (imprensa maiúscula), e do outro lado, o nome e o sobrenome em letra imprensa (bastão) e cursiva (manuscrita). Você acha que este tipo de trabalho pode prejudicar na aprendizagem das crianças que apresentam maior dificuldade?<br /><br />
    <b>Rosa:</b> Na verdade não há restrição nenhuma em o professor colocar no mesmo cartão o primeiro nome com letra bastão e do outro lado colocar o nome completo também com letra de forma, pois é importante a criança conhecer o seu nome completo. Mas, quando o professor vai problematizar, quando vai fazer atividades com as crianças, deve utilizar o primeiro nome, escrito em letra bastão. Em relação à letra cursiva, na realidade não há necessidade de você colocar letra cursiva nesse momento. A letra cursiva é utilizada apenas no momento que as crianças já apresentam uma escrita alfabética. Há casos até de crianças que quando estão aprendendo a ler e a escrever têm interesse pela letra cursiva. Então, às vezes o professor coloca a criança para copiar o nome, copiar a rotina do dia, as atividades que vai fazer, para satisfazer esse desejo dela, mas são casos muito pontuais. Usamos a letra maiúscula porque é o que ajuda a criança a pensar sobre o sistema alfabético, e a letra cursiva deixamos para mais tarde. Além do mais, é muito mais fácil identificar quantas letras tem uma palavra em uma letra de forma do que em uma letra cursiva. Por exemplo, ao escrever BANANA, tem criança que acha que cada movimento que você faz do "n" é uma letra. Isso atrapalha a criança. Por isso recomendamos que os professores usem a letra de forma, que é a que mais ajuda as crianças.<br /><br />
    <b>Além das Letras:</b> Mesmo sabendo que o trabalho com o nome é muito importante, muitos profissionais não desenvolvem projetos de trabalho em que o nome próprio é trabalhado. Isso é o que a professora Renata observa. Então ela pergunta: você acredita que isso seja um dos fatores para o enorme número de crianças que estão cursando o 5º ano e não são alfabetizadas? Até que ponto a omissão desse trabalho interfere na vida do dos alunos?<br /><br />
    <b>Rosa:</b> Não é pela falta de trabalhos com os nomes que os meninos não se alfabetizam. Isso acontece porque não são utilizadas propostas boas de aprendizagem para que eles possam aprender a ler e escrever, assim como há muitas crianças que aprenderam a ler e escrever sem necessariamente terem trabalhado com o nome de uma forma tão sistemática assim. Nós estamos passando por um momento em que os professores estão aprendendo a trabalhar sem as famílias silábicas, que ainda aparecem em algumas cartilhas ou que fazem parte de alguns métodos de alfabetização. Hoje os professores estão aprendendo que pra ensinar os meninos a ler e escrever, é preciso trabalhar com o texto, com a palavra, com a letra e com a sílaba. Eles estão aprendendo que para ensinar as crianças, nós precisamos identificar quais os saberes que elas já possuem para, a partir daí, organizar boas situações de aprendizagem. Hoje sabemos que aprender a ler e a escrever se aprende lendo e escrevendo. <br /><br />
    <b>Além das Letras:</b> Mas, se o trabalho com o nome não é tudo, o que mais os professores precisam fazer?<br /><br />
    <b>Rosa:</b> Acreditar que um aluno não alfabetizado é capaz de ler é uma coisa que tem exigido um esforço muito grande dos professores. Exige que ele entenda que não se aprende memorizando que o BO com BO dá BOBO. Hoje nós já sabemos que aluno que não está alfabetizado, mas tem conhecimento sobre o valor sonoro, é capaz de identificar um nome em uma lista. É possível pedir a eles que, por exemplo, diante de uma lista de animais, possa identificar os que estão em extinção. Ele pode localizar esses nomes utilizando estratégias de leitura onde ele seleciona a letra inicial, a letra final, vai inferindo, verificando. Então, ele está lendo. Hoje nós temos claro que ler ensina a ler e escrever. Acreditar que um aluno possa ler ainda é difícil para os professores. Quando eu vou discutir com os meus colegas, eu encontro muito mais atividades de escrita do que atividades de leitura e digo que é preciso ter um equilíbrio entre essas atividades. Mas, infelizmente, os meninos chegam no ciclo 2 não alfabetizados por falta de um investimento adequado. Nós já sabemos que esses alunos chegam na escola com pouca informação sobre a leitura e a escrita. Então, a escola precisa inundar esses alunos de muita leitura escrita, trabalhar muito com projetos, trabalhar com leitura escrita de diferentes gêneros textuais e trabalhar muito com situações que permitam o aluno refletir sobre a escrita convencional e sobre a própria escrita. O nome é apenas um dos recursos que ajudam nesse trabalho.<br /><br />
    <b>Além das Letras:</b> E os pais? Como fazer os pais compreenderem o trabalho que não é calcado no que convencionalmente estão acostumados? Como fazer uso adequado do caderno numa proposta de trabalho por agrupamento e reflexão? Essa é uma dificuldade que a professora Érika sempre encontra.<br /><br />
    <b>Rosa:</b> É muito importante que na reunião de pais, nós expliquemos as mudanças que vêm ocorrendo em nosso trabalho de sala de aula. Porque os pais querem que seus filhos aprendam da forma como eles aprenderam, eles vêm com essa representação. Nós temos que ir explicando que o conhecimento avança em todas as áreas: na medicina, na educação, na engenharia. O outro ponto é a qualidade do nosso trabalho. É ela que vai dando segurança para os pais. Há muitas formas de comunicar aos pais sobre o que ocorre na escola. Quando professora, eu fazia um diário com as crianças onde contava o que acontecia durante a semana e as crianças o levavam todo dia para casa. Então, quando eu escrevia lá no diário: "Hoje jogamos boliche. Foi uma atividade muito interessante porque além do jogo, as crianças registravam seus pontos em uma tabela, faziam cálculo mental,...", todos os pais sabiam que não se tratava do jogo pelo jogo, mas que haviam outros conteúdos sendo trabalhados. O caderno do aluno é um outro registro importante do trabalho realizado. Muitas vezes os professores propõem atividades para as quais as crianças não utilizam o caderno. Então é comum que os pais estranhem e pensem que os filhos não fizeram nada, só brincaram o dia todo ou então conversaram a aula toda. Mas, como nós já sabemos que os pais têm essa representação, antecipamos algumas saídas. <br /><br />
    <b>Além das Letras:</b> Os pais podem não entender muito da proposta, mas eles acompanham o caderno dos filhos, não é? <br /><br />
    <b>Rosa:</b> É importante ter um caderno bonito, arrumado. Até 2005, quando eu era professora, eu tinha o hábito de inaugurar o caderno com os alunos. No primeiro dia de aula, eu levava cadernos para todos: para quem não tinha, a escola dava um. Chegando perto do final do dia, depois de tantas coisas que já havíamos feito juntos, eu anunciava ao grupo o momento de usar o caderno novo. Era uma felicidade! As crianças acreditam que iam aprender a ler e a escrever no primeiro dia de aula. Usar o caderno, então, era uma alegria geral. Eu perguntava: "o que nós já fizemos hoje?". E então eles relatavam tudo: "fizemos a roda de conversa, depois você leu uma história, fomos visitar a escola e tirar fotos, fizemos uma brincadeira no pátio, tomamos lanche e agora vamos usar o caderno". Eu escrevia tudo o que as crianças falaram na lousa: era a agenda do dia, com tudo aquilo que nós fizemos e o que nós ainda faríamos até o final do período. Todas as crianças escreviam a agenda no caderno, o que provocava a sensação de "olha, eu estou escrevendo". Era uma forma de mostrar que a escrita é uma extensão da memória, que nós vamos poder recordar no outro dia ou no futuro o que a gente fez no primeiro dia de aula, essa coisa de poder copiar, de escrever, de poder comunicar aos pais o que tinha feito. Todos os dias as crianças escreviam a agenda do dia. Parte dela nós planejávamos em conjunto, outra parte era uma proposta que eu levava. Eu percebia que isso causava um impacto, todo mundo com caderno em mãos logo no primeiro dia. <br /><br />
    <b>Além das Letras:</b> Mas esse caderno é mesmo tão importante para a criança?<br /><br />
    <b>Rosa:</b> Sim, é. E há muito que aprender. Usar o caderno é uma convenção, precisa ser ensinada, trabalhada. O que a prática mostrou para mim é que começando as aulas em fevereiro, no final de abril as crianças começam a ter mais autonomia para usar o caderno sem te perguntar tanto. Mas você precisa todo dia ficar falando: "abre o caderno na ultima lição, passa um traço, não pode pular folha, não pode pular parte...". Por outro lado, é interessante equilibrar um pouco as propostas que exigem o uso do caderno e as que não fazem uso. Haverá dias que o professor só tem a agenda do dia registrada no caderno porque trabalhou com projetos, escreveu em outros lugares, em outros materiais. Em um dia pode não haver nada de Língua Portuguesa, mas sim de Matemática, ou então de uma outra área que o professor esteja trabalhando. <br /><br />
    <b>Além das Letras:</b> Para finalizar, Rosa, vamos trazer as observações e as perguntas da professora Raquel: considerando que o trabalho pedagógico com o nome próprio é imprescindível para a realização de um trabalho eficaz com a alfabetização de crianças e/ou adultos em qualquer idade escolar, como poderíamos compartilhar de forma mais eficiente nosso trabalho pedagógico a fim de que nossos colegas se sintam motivados a realizar tais atividades com suas turmas? Como conquistar nossos colegas a propor essas atividades, sabendo que é uma forma infalível de se obter resultados satisfatórios, uma vez que o nome próprio traz em sua essência o valor e a função de um modelo de escrita que nenhum outro proporciona?<br /><br />
    <b>Rosa:</b> O que minha prática tem mostrado é que o que fazemos contamina os nossos colegas, porque eles podem ver que os nossos alunos aprendem mais e melhor da forma que nós trabalhamos. Na verdade todo professor quer que seu aluno aprenda, ele trabalha nessa direção. Só que quando ele vê que as crianças da outra classe estão aprendendo mais e melhor, porque o professor faz um trabalho diferente, isso o incomoda e aí ele começa a se interessar. Eu já passei por essa experiência. Na escola, nós éramos um grupo de 4 pessoas e, entre elas, havia uma amiga que trabalhava com cartilhas, extremamente tradicional, mas muito séria, muito dedicada. Eu trabalhei 4 anos com ela e foi interessante vê-la mudando gradativamente. No primeiro ano, paralelo ao trabalho, ela começou a ler mais para os alunos. Eu contava o que eu lia, quais eram os livros, o critério de escolha dos livros. A partir daí ela pedia alguns emprestados para ler, começou a deixar os alunos folhearem os livros. No outro ano ela começou a falar assim: "Você pode me dar uma cópia da suas atividades?" No terceiro ano ela informou aos pais que não ia mais utilizar a cartilha. Mas, como ela tinha a cartilha na cabeça, acabou entrando em contradição, alternando aquelas atividades da cartilha com outras que ela me via desenvolvendo em sala. No quarto ano, finalmente, nós já estávamos trabalhando juntas e integradas. É o resultado do nosso trabalho que vai fazendo com que outros professores vejam que essa é a melhor forma de trabalhar com os alunos, quando trabalhamos com a língua verdadeiramente. Quanto mais as nossas práticas se aproximarem de situações de uso, de situações reais, melhor as crianças aprenderão e é isso que precisamos compartilhar com os nossos colegas.<br /><br />
    <br />
    <br />
    <a href="javascript:history.go(-1)"><img src="img/icone_voltar.png"/></a>
    </p>
</div>

<?php
	include("includes/footer.php");
?>